# Generated by Django 3.2 on 2021-05-06 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210506_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 4, 21, 9, 383001, tzinfo=utc)),
        ),
    ]
